{{- if .Values.ingress.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  labels:
    app: {{ template "orange_web.name" . }}
    chart: {{ template "orange_web.chart" . }}
    heritage: {{ .Release.service }}
    release: {{ .Release.Name }}
  name: {{ template "orange_web.fullname" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "orange_web.fullname" . }}
          servicePort: {{ .Values.service.port }}
        path: {{ .Values.ingress.path }}
{{ end -}}
