---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "orange_web.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "orange_web.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    chart: {{ .Chart.Name }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "orange_web.fullname" . }}-rolebinding
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ template "orange_web.fullname" . }}
    chart: {{ .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "orange_web.fullname" . }}-sa
  namespace: "{{.Release.Namespace}}"
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ template "orange_web.fullname" . }}-role
  apiGroup: ""

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: "{{.Release.Namespace}}"
  name: {{ template "orange_web.fullname" . }}-role
  labels:
    app: {{ template "orange_web.fullname" . }}
    chart: {{ .Chart.Name }}
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]
